### ISSUE TITLE
Use wikEdDiff for diff screenshot instead

### ISSUE THREAD

**Issue by Artoria2e5** [edsu/anon#163]
[wikiEdDiff](https://en.wikipedia.org/wiki/User:Cacycle/wikEdDiff) provides a more space-efficient inline diff mode, which should make the diff images more readable. To reduce image size, the "normal" diff elements should be excluded, leaving only two `tr` elements: one with `.diff-otitle` and the other with `#wikEdDiffWrapper`.

![image](https://user-images.githubusercontent.com/6459309/32790985-e0553d0c-c92d-11e7-81e3-62bc5901990e.png)

**Comment by edsu** [comment]
This would require an anon instance to be associated with a Wikipedia account, and to login, so that a diff is viewed with that user script?

This seems like a lot of overhead for a small improvement. It also could be dissonant for users who do not have that user script installed. What they see on Twitter will be different from what they see when clicking the link to the diff.
